# Name of this workflow
name: CI/CD Pipeline

# This workflow gets triggered upon a push event on the main branch
on:
  push:
    branches: [ main ]

# Jobs are the tasks that this workflow will run
jobs:
  # Lint job, checks for syntax errors and best practices
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
    # Checks out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    # Sets up Go environment for use in actions
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'  
    # Installs the linter
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
    # Runs the linter
    - name: Lint
      run: golangci-lint run

  # Test job, tests the Go code across different platforms and Go versions
  test:
    name: Test Across Matrix
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    # Sets up Go environment for use in actions
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    # Checks out your repository under $GITHUB_WORKSPACE
    - name: Checkout code
      uses: actions/checkout@v2
    # Runs the tests
    - name: Test
      run: go test ./...

  # Build and Publish job, builds the Docker image and pushes it to DockerHub
  build-and-publish:
    name: Build and Publish Docker Image
    # This job depends on the lint and test jobs
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    # Checks out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v3
    # Builds the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    # Publishes the Docker image to DockerHub
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: paulweaver101/ci-cd
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
