name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    ## checks out our project source code
    - uses: actions/checkout@v3
    
    ## Builds our docker image!
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    ## Publishes our image to Docker Hub 😎
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        ## the name of our image
        name: paulweaver101/ci-cd
        ## Here we pass in our Docker Username
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        ## and our Docker password which 
        password: ${{ secrets.DOCKERHUB_TOKEN }}